pipeline {
  agent any
  stages {

    stage('Check Jenkins User') {
            steps {
                script {
                    def jenkinsUser = sh(script: 'whoami', returnStdout: true).trim()
                    echo "Jenkins is running the pipeline as user: ${jenkinsUser}"
                }
            }
    }
            
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
